### ISSUE TITLE
Add timeout functionality

### ISSUE THREAD

**Issue by gregdek** [ansibull/ansibullbot#1]
Here's the workflow, I think:

* Issue touched by no one in two weeks?
  + If community_review and new_plugin, ignore (we need something better here)
  + If community_review and not new_plugin and not pending_action:
    - If <=2 last comments are bot pings, ping maintainer
    - If >2 last comments are bot pings, put in pending_action
  + If community_review and not new_plugin and pending_action:
    - Flag "orphaned" (and figure this process out!)
  + If core_review, touch ("still waiting for core team, thx for your patience") and move on.
  + If needs_* and not pending_action, put in pending_action
  + If needs_* and pending_action, close

**Comment by robynbergeron** [comment]
If community_review and new_plugin and more than 2 weeks, (give_me_love)? 

Where give_me_love (or something that sounds less cheeky) could be:
* send a reminder mail to $somewhere saying plz tweet about me
* automagically post to a file / wiki / perma-blog / etc. of "things needing love" (aka: things you can do to make a difference!) (also: modules with no maintainers could go on this list)

**Comment by gregdek** [comment]
Is this specifically for the new module case?
