### ISSUE TITLE
core/2230 broken: mishandles rebase detection

### ISSUE THREAD

**Issue by gregdek** [ansibull/ansibullbot#6]
Seems as though we're not handling needs_rebase correctly:

(This example may be outdated quickly)

https://api.github.com/repos/ansible/ansible-modules-core/pulls/2230 
...shows that pull['mergeable'] should be 'false'.

But we don't detect it. Why not?

**Comment by robynbergeron** [comment]
I can't quite tell, but: are you sure it's looking for mergeable: in the actual pulls/#number api data and not just the full-on list of what you dumped from https://api.github.com/repos/ansible/ansible-modules-core/pulls (or extras)? 

It looks like it's supposed to be getting it from the PR api URL itself but if that somehow got hosed up... mergeable: isn't a field that shows up in the blast of json from ttps://api.github.com/repos/ansible/ansible-modules-core/pulls.

**Comment by gregdek** [comment]
Look at lines 54-62: we do a pull of the whole set of PRs, and then for each PR in the list r, we then do a second pull of the longer pull data -- and this was added explicitly to get the mergeable field. I verified that the mergeable data is there, but it's not parsing it right.

**Comment by robynbergeron** [comment]
I was 99.9% sure that was what it was supposed to be doing (YAY I CAN READ CODE WOOT). If it's actually showing up in your dump to /tmp then ... comma comma shrug?

Maybe a break at the end of the gigantic if / else loop magic at line 182?
